# -*- coding: utf-8 -*-
"""stt_owsm_v4_small_370M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5mmVIbO1AvVULGSMGfiF8PVk-JpmAi0
"""

pip install espnet soundfile espnet_model_zoo

"""## Local Inference on GPU
Model page: https://huggingface.co/espnet/owsm_v4_small_370M

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/espnet/owsm_v4_small_370M)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

import soundfile as sf
import os

# Create a dummy WAV file for demonstration if it doesn't exist
if not os.path.exists('speech.wav'):
    # Generate a simple sine wave as an example
    samplerate = 16000  # Sample rate (Hz)
    duration = 3      # Duration (seconds)
    frequency = 440   # Frequency (Hz)

    import numpy as np
    t = np.linspace(0., duration, int(samplerate * duration), endpoint=False)
    amplitude = 0.5
    data = amplitude * np.sin(2. * np.pi * frequency * t)

    # Save to 'speech.wav'
    sf.write('speech.wav', data, samplerate)
    print("Generated a sample 'speech.wav' file.")
else:
    print("Using existing 'speech.wav' file.")

import urllib.request

# URL to a sample wav file containing actual speech
url = "https://www.kozco.com/tech/LRMonoPhase4.wav"
speech_file = "speech.wav"

print(f"Downloading sample speech from {url}...")
urllib.request.urlretrieve(url, speech_file)
print(f"Saved as {speech_file}. You can now run the transcription cell again.")

from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.asr_inference import Speech2Text
import yaml
import tempfile
import os
import glob

# 1. Download model files
d = ModelDownloader()
kwargs = d.download_and_unpack("espnet/owsm_v4_small_370M")

# 2. Identify the config file path
# Often download_and_unpack returns the path in 'asr_train_config' or 's2t_train_config'
config_path = kwargs.get('asr_train_config') or kwargs.get('s2t_train_config')

if not config_path:
    # Fallback: search for config.yaml in the downloaded directories
    search_path = os.path.join(d.cachedir, "**", "config.yaml")
    found_configs = glob.glob(search_path, recursive=True)
    if found_configs:
        config_path = found_configs[0]

# 3. Clean the config file
if config_path:
    with open(config_path, 'r') as f:
        config_data = yaml.safe_load(f)

    def remove_key_recursive(obj, key):
        if isinstance(obj, dict):
            obj.pop(key, None)
            for v in obj.values():
                remove_key_recursive(v, key)
        elif isinstance(obj, list):
            for item in obj:
                remove_key_recursive(item, key)

    print(f"Cleaning config at {config_path}...")
    remove_key_recursive(config_data, 'sym_na')

    # Create a new temporary config file
    fd, temp_path = tempfile.mkstemp(suffix=".yaml")
    with os.fdopen(fd, 'w') as f:
        yaml.safe_dump(config_data, f)

    # Update kwargs for initialization
    kwargs['asr_train_config'] = temp_path

# 4. Final adjustments to kwargs keys
if 's2t_model_file' in kwargs:
    kwargs['asr_model_file'] = kwargs.pop('s2t_model_file')
if 's2t_train_config' in kwargs:
    del kwargs['s2t_train_config']

# Filter out any keys that Speech2Text doesn't accept
# (Sometimes model_zoo adds extra metadata keys)

print("Initializing model...")
try:
    model = Speech2Text(**kwargs)
    print("Model loaded successfully!")
except Exception as e:
    print(f"Failed: {e}")
    raise e

import soundfile as sf

# Load the new audio file containing actual speech
speech, rate = sf.read('speech.wav')

# Perform inference
print("Transcribing real speech sample...")
results = model(speech)

if results:
    text, *_ = results[0]
    print(f"\nTranscribed Text: {text}")
else:
    print("No transcription results found.")