# -*- coding: utf-8 -*-
"""Copy of owsm_v4_small_370M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FI1W1XHLJ0YjBHDjUCLqMgOzYwEpbv9X
"""

# 1. Install the updated, maintained version of the library
!pip install coqui-tts

# 2. Install the Japanese dictionary support (often required by the API)
!pip install unidic-lite mecab-python3

import torch
# Note the change from 'TTS.api' to 'coqui_tts.api' if using the fork
# though many forks maintain the 'TTS' namespace for compatibility.
try:
    from TTS.api import TTS
except ImportError:
    from coqui_tts.api import TTS

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Example: Load the standard XTTS v2 model
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

# 1. Install the core phonemizer and English support specifically
!pip install gruut gruut_lang_en

# 2. Install phonemizer (this is a common wrapper TTS uses)
!pip install phonemizer

# 3. Install the system-level espeak library (Crucial for Colab)
!apt-get install -y espeak-ng

!pip install gruut gruut-lang-en

# 2. Force a refresh of the internal package metadata
import site
from importlib import reload
reload(site)

# 3. Double-check if gruut can be seen now
try:
    import gruut
    print("✅ Gruut is now installed and accessible!")
except ImportError:
    print("❌ Gruut is still missing. Trying one more fix...")
    !pip install --no-cache-dir gruut gruut-lang-en

from TTS.api import TTS
import torch

# This time, it should see Gruut immediately upon import
device = "cuda" if torch.cuda.is_available() else "cpu"
tts = TTS("tts_models/en/ljspeech/glow-tts").to(device)

tts.tts_to_file(text="The phonemizer is finally working properly.", file_path="output.wav")

from IPython.display import Audio
Audio("output.wav", autoplay=True)

!pip install huggingface_hub

from huggingface_hub import login

# This will create an input box for your token
login()

from huggingface_hub import snapshot_download
import os

# Create a folder for the model
model_path = "./kinyarwanda_health_model"
os.makedirs(model_path, exist_ok=True)

# Download the model files
snapshot_download(
    repo_id="DigitalUmuganda/xtts_based_male_female_health_model",
    local_dir=model_path
)

# Look for any wav file in the model directory
import glob
samples = glob.glob(f"{model_path}/**/*.wav", recursive=True)
if samples:
    speaker_wav = samples[0]
    print(f"✅ Found a sample to use: {speaker_wav}")
else:
    # If no sample found, we'll download a generic one
    !wget -O reference.wav https://github.com/coqui-ai/TTS/raw/main/TTS/demos/multilingual/speaker_1.wav
    speaker_wav = "reference.wav"
    print("✅ Downloaded a generic reference sample.")

import torch
import torchaudio
import os
from TTS.api import TTS
from IPython.display import Audio

# 1. FORCE DELETE the corrupted file if it exists
if os.path.exists("reference.wav"):
    os.remove("reference.wav")

# 2. Download a GUARANTEED valid wav file (LibriSpeech sample)
# This uses a direct link to a real audio file
!wget -q -O reference.wav https://www.pacdv.com/sounds/voices/maybe-next-time.wav

# 3. Setup paths
model_path = "./kinyarwanda_health_model"
speaker_wav = "reference.wav"

# 4. Load the model (Only if not already loaded)
try:
    if 'tts' not in locals():
        tts = TTS(model_path=model_path, config_path=os.path.join(model_path, "config.json")).to("cuda")
    model = tts.synthesizer.tts_model
except Exception as e:
    print(f"Model Load Error: {e}")

# 5. Manual Inference
def speak_kinyarwanda(text_to_speak, output_name="kinyarwanda_final.wav"):
    print("Processing audio...")
    # Get voice characteristics
    gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=speaker_wav)

    # Run inference using "en" as the proxy language
    out = model.inference(
        text_to_speak,
        "en",
        gpt_cond_latent,
        speaker_embedding,
        temperature=0.7,
        repetition_penalty=5.0
    )

    wav = torch.tensor(out['wav']).unsqueeze(0)
    torchaudio.save(output_name, wav, 24000)
    return output_name

# 6. Run it
text = """
  Ikoranabuhanga ni umusingi w'iterambere rirambye
"""
try:
    file = speak_kinyarwanda(text)
    print(f"✅ Success! Created {file}")
    display(Audio(file, autoplay=True))
except Exception as e:
    print(f"❌ Generation Error: {e}")